export const bikes = [
    { id: 1, name: "RapidFire", model: "SpeedMaster" },
    { id: 2, name: "Thunderbolt", model: "PowerBlade" },
    { id: 3, name: "ShadowRider", model: "StealthX" },
    { id: 4, name: "BlazeEdge", model: "InfernoX" },
    { id: 5, name: "SkyStriker", model: "AeroX" },
    { id: 6, name: "NightHawk", model: "ShadowX" },
    { id: 7, name: "GhostRider", model: "SpectreX" },
    { id: 8, name: "SilverBullet", model: "SwiftX" },
    { id: 9, name: "PhoenixFury", model: "FireBlade" },
    { id: 10, name: "StormChaser", model: "TempestX" },
    { id: 1, name: "RapidFire", model: "SpeedMaster" },
    { id: 2, name: "Thunderbolt", model: "PowerBlade" },
    { id: 3, name: "ShadowRider", model: "StealthX" },
    { id: 4, name: "BlazeEdge", model: "InfernoX" },
    { id: 5, name: "SkyStriker", model: "AeroX" },
    { id: 6, name: "NightHawk", model: "ShadowX" },
    { id: 7, name: "GhostRider", model: "SpectreX" },
    { id: 8, name: "SilverBullet", model: "SwiftX" },
    { id: 9, name: "PhoenixFury", model: "FireBlade" },
    { id: 10, name: "StormChaser", model: "TempestX" },
];